config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  get 'home/about'
  resources :users, only: [:show,:index,:edit,:update]do
  	resources :relationships, only:[:create, :destroy]
  	get "follows" =>  'relationships#follows'
  	get "follower" => 'relationships#follower'
end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  get '/search' => 'search#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
    	favorites.where(user_id: user.id).exists?
  	end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: 'User'
	belongs_to :followed, class_name: 'User'

	validates :follower_id, presence: true
	validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image, destroy: false

  has_many :follower, class_name:"Relationship", foreign_key:"follower_id", dependent: :destroy
  has_many :followed, class_name:"Relationship", foreign_key:"followed_id",dependent: :destroy
  has_many :following_user,through: :follower, source: :followed 
  has_many :follower_user, through: :followed, source: :follower#

  def following?(user)
    following_user.include?(user)
  end

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	def create
		book = Book.find(params[:book_id])
		comment = current_user.book_comments.new(book_comment_params)
		comment.book_id = book.id
		comment.save
		redirect_to request.referer
	end

	def destroy
		BookComment.find_by(id:params[:id], book_id: params[:book_id]).destroy
		redirect_to request.referer
	end
private
 	def book_comment_params
 		params.require(:book_comment).permit(:comment)
 	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
      if @book.user == current_user
        render "edit"
      else
        redirect_to books_path
      end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		@book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: @book.id)
		favorite.save
		redirect_to request.referer
	end

	def destroy
		@book = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id: @book.id)
		favorite.destroy
		redirect_to request.referer
	end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def create
		current_user.follow(params[:user_id])
	end

	def destroy
		current_user.unfollow(params[:user_id])
	end

	def follows
		user = User.find(params[:user_id])
		@users = user.following_user

	end

	def follower
		user = User.find(params[:user_id])
		@users = user.follower_user
	end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	before_action :authenticate_user!

	def search
		@model = params["search"]["model"]
		@content = params["search"]["content"]
		@how = params["search"]["how"]
		@datas = search_for(@model,@content,@how)
	end
private
	def match(model,content)
	  	if model == 'user'
	  		User.where(name:content)
	  	else model == 'book'
	  		Book.where(title:content)
	  	end
	end

	def forward(model,content)
	  	if model == 'user'
	  		User.where("name LIKE?","#{content}%")
	  	else model == 'book'
	  		Book.where("title LIKE?","#{content}%")
	  	end
	end

	def backword(model,content)
		if model == 'user'
			User.where("name LIKE?","%#{content}")
		else model == 'book'
			Book.where("title LIKE?","%#{content}")
		end
	end

	def partical(model,content)
		if model == 'user'
			User.where("name LIKE?","%#{content}%")
		else model == 'book'
			Book.where("title LIKE?","%#{content}%")
		end
	end

	def search_for(model,content,how)
		case how
			when 'match'
				match(model,content)
			when 'forward'
				forward(model,content)
			when 'backword'
				backword(model,content)
			when 'partical'
				partical(model,content)
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(current_user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.js.erb
$("#comments_area").html('<%= j(render "book_comments/create" ) %>')

app/views/book_comments/destroy.js.erb
$("#comment-delete").html('<%= j(render "book_comments/dastroy" ) %>')

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %>
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/_post_books.html.erb
<% books.each do |book| %>
	<tr>
		<td>
			<%= link_to user_path(book.user) do %>
				<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
			<% end %>
		</td>
		<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
		<td><%= book.body %></td>
		<!-- いいね機能 -->
		<td id="follow-link-<%= book.id %>">
			<% if book.favorited_by?(current_user) %>
				 <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
				    <span class="fas fa-heart"><%= book.favorites.count %></span>
				 <% end %>
			<% else %>
				 <%= link_to book_favorites_path(book), method: :post, remote: true do %>
				    <span class="far fa-heart"><%= book.favorites.count %></span>
				 <% end %>
			<% end %>
		</td>
		<td>
			コメント数：<%= book.book_comments.count %>
		</td>
	</tr>
	<% end %>

app/views/books/_post_comment.html.erb
<table>
	<% book.book_comments.each do |comment| %>
	  	<tr>
			<td class="comment-item">
				<%= attachment_image_tag(comment.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %><br>
					<%= comment.user.name %>
			</td>
			<td class="comment-item"><%= comment.comment %></td>
			<td class="comment-item">
				<% if current_user.id == comment.user_id %>
					<%= link_to "Delete", book_book_comment_path(comment.book, comment),id: "comment-delete",class: "btn btn-danger", method: :delete %>
				<% end %>
			</td>
		</tr>
	<% end %>
</table>
<div id="comments_area">
	<%= form_with(model: [book, book_comment]) do |f| %>
		<%= f.text_area :comment, class: "col-xs-12",rows:'5' %>
		<%= f.submit "送信"%>
	<% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><strong>
      <%= @book.errors.count %>errors prohibited this book from being saved:
    </strong></h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  </div>
<% end %>

<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>

		<%= render "books/newform", book: @book %>
		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><strong>
      <%= @book.errors.count %>errors prohibited this book from being saved:
    </strong></h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  </div>
<% end %>

<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<%= render 'books/post_books', books: @books %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @book.user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book_new %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@book.user) do %>
							<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, book_path(@book) %></td>
					<td><%= @book.body %></td>
					<!-- いいね機能 -->
					<td  id="follow-link-<%= @book.id %>">
						<% if @book.favorited_by?(current_user) %>
							 <%= link_to book_favorites_path(@book), method: :delete,remote: true do %>
							    <span class="fas fa-heart"><%= @book.favorites.count %></span>
							 <% end %>
						<% else %>
							 <%= link_to book_favorites_path(@book), method: :post,remote: true do %>
							    <span class="far fa-heart"><%= @book.favorites.count %></span>
							 <% end %>
						<% end %>
					</td>
					<td>
						コメント数：<%= @book.book_comments.count %>
					</td>

					<% if @book.user == current_user %>
					  <td><%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					  <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger" %></td>
					<% end %>
				</tr>
			</table>
			<!-- コメント機能 -->
			<div>
			  <%= render 'books/post_comment', book: @book, book_comment: @book_comment %>
			</div>
	</div>
</div>

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>

app/views/relationships/create.js.erb
$("<%= @id_name %>").html('<%= escape_javascropt(render("relationships/create")) %>')

app/views/relationships/destroy.js.erb
$("<%= @id_name %>").html('<%= escape_javascropt(render("relationships/destroy",)) %>')

app/views/relationships/follower.html.erb
<h2>Foollower Users</h2>
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th>Image</th>
			<th>Name</th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback:'no-image-mini.jpg') %></td>
			<td><%= user.name %></td>
			<td>フォロー数：<%= user.following_user.count %></td>
			<td>フォロワー数：<%= user.follower_user.count %></td>
			<td><%= link_to "Show", user_path(user) %></td>
		</tr>
	<% end %>
</table>

app/views/relationships/follows.html.erb
<h2>Foollows Users</h2>
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th>Image</th>
			<th>Name</th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback:'no-image-mini.jpg') %></td>
			<td><%= user.name %></td>
			<td>フォロー数：<%= user.following_user.count %></td>
			<td>フォロワー数：<%= user.follower_user.count %></td>
			<td><%= link_to "Show", user_path(user) %></td>
		</tr>
	<% end %>
</table>

app/views/search/search.html.erb
<% if @model == 'user' %>
  <table class="table">
  	<thead>
  	  <tr>
  		<th>Image</th>
		<th>Name</th>
		<th colspan="3"></th>
	  </tr>
  	</thead>
		<% @datas.each do |user| %>
	  	<tr>
	  		<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: 'no-image-mini.jpg') %></td>
	  		<td><%= user.name %></td>
	<% end %>
<% else %>
	<table class="table">
	  	<thead>
	  	  <tr>
	  		<th></th>
			<th>Title</th>
			<th colspan="3">Opinion</th>
		  </tr>
	  	</thead>
		  <% @datas.each do |book| %>
			<tr>
			  <td><%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: 'no-image-mini.jpg') %></td>
			  <td><%= book.title %></td>
			  <td><%= book.body %></td>
	<% end %>
<% end %>

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
	<tr>
		<th>Follows</th>
		<th>
			<%= link_to user_follows_path(user) do %>
				<%= user.following_user.count %>
			<% end %>
		</th>
	</tr>
		<th>Follower</th>
		<th>
			<%= link_to user_follower_path(user) do %>
				<%= user.follower_user.count %>
			<% end %>
			</th>
</table>
<% if user != current_user %>
<!-- フォロー機能 -->
	<% if current_user.following?(user) %>
		<%= link_to "フォロー解除", user_relationship_path(user.id),class: "btn btn-primary",method: :delete %>
	<% else %>
		<%= link_to "フォローする", user_relationships_path(user.id),class: "btn btn-primary",method: :post %>
	<% end %>
<% else %>
	<div class="row">
		<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	</div>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-xs-3">
	<h2>User info</h2>
	 <%= render 'users/profile', user: current_user %>

	<h2>New book</h2>
	<%= render 'books/newform', book: @book %>
  </div>

  <div class="col-xs-9">
	<h2>Users</h2>
	<!--users一覧 -->
	<table class="table">
		<thead>
			<tr>
				<th>image</th>
				<th>name</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @users.each do |user| %>
			<tr>
				<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
				<td><%= user.name %></td>
				<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
<!--users一覧 -->
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<%= render 'books/post_books', books: @books %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>